
MethodLength:
    Max: 200

LineLength:
    Max: 160

PerceivedComplexity:
    Enabled: false

CyclomaticComplexity:
    Enabled: false

AbcSize:
    Enabled: false

ClassLength:
    Enabled: false

IfUnlessModifier:
    Enabled: false

RegexpLiteral:
    Enabled: false

